### ISSUE TITLE
value got drop because of Float data type

### ISSUE THREAD

**Issue by underdogenglish** [wso2-extensions/siddhi-map-keyvalue#41]
Description:

5.1.2:

Window

Steps to reproduce:
I have follow the WSO2 Streaming Integrator document is fine to run the CDC. The issue is when I set the "define stream" type string or integer the CDC is normal but when I set the float type, the error as below.

Error Message:
ERROR {io.siddhi.extension.map.keyvalue.sourcemapper.KeyValueSourceMapper} - Message {MemberId=1000000022, Date=1594574917953, price=-500.5, price2=2000.1} contains incompatible attribute types and values. Value 2000.1 is not compatible with type FLOAT,Hence dropping the message

Code
**@app:name('MemberAPP')
@app:description('Test for member')

@source(type = 'cdc', url = "jdbc:sqlserver://localhost:1433;databaseName=Member", username = "xxx", password = "xxx", table.name = "dbo.MemberData", operation = "insert", connector.properties = "snapshot.mode=initial_schema_only", database.server.name = "localhost\default",
@Map(type = 'keyvalue'))
define stream test(MemberId int, price float, price2 float, Date string);

@sink(type = 'log',
@Map(type = 'passThrough'))
define stream Account (MemberId int, price float, price2 float, Date string);

@info(name = 'TotalShow')
from test
select *
insert into Account;**

**Comment by AnuGayan** [comment]
This issue was fixed by https://github.com/siddhi-io/siddhi-map-keyvalue/pull/44 and https://github.com/siddhi-io/siddhi-map-keyvalue/pull/43
